version: "3"

volumes:
  db-volume: {}

services:
  db:
    image: postgres:9.6
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
